# sudo level privileges required
sudo: required 
# the docker service is needed
services: 
    - docker
# before running the test or production steps, we need some commands to be carried out
before_install: 
    - docker build -t tangolf88/aws-and-travis -f Dockerfile.dev .

# any return value other than 0 will mean that the script failed and travis will return a failed operation
script:
    - docker run -e CI=true tangolf88/aws-and-travis npm run test

# once the script has passed the deployment can be run
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "travis-and-aws"
    env: "TravisAndAws-env"
    bucket_name: "elasticbeanstalk-us-east-1-259629792391"
    bucket_path: "travis-and-aws"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY